# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c738138a9125de2a6be923cbd2c44b2720ee56021466111c06b0e1922f5604b9ada0da3fe4293112218310a6db2fde3c1494cf9f82b702f9b7dd13922e37721

test:
  secret_key_base: d53def6b58cade550e975c5374c7bb344d40534f8b394328fa700a19cc4f9a7a21e56e2bebab51d8537b353af33e7ba9e8fe58b825771ebe6c992fb054c0ca62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
